#theme: jekyll-theme-tactile
#remote_theme: poole / lanyon
#remote_theme: poole / hyde
#remote_theme: sharu725/online-cv
#remote_theme: jitinnair1/gradfolio
#remote_theme: hydecorp/hydejack
theme: minima


header_pages:
  - about.md
  - cv.md
  - research.md

sidebar:
    about: True # set to False or comment line if you want to remove the "how to use?" in the sidebar
    education: True # set to False if you want education in main section instead of in sidebar

    # Profile information
    name: Harry Aginta
    tagline: PhD student at Nagoya University, Japan
    avatar: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

    # Sidebar links
    email: aginta.harry@c.mbox.nagoya-u.ac.jp
    linkedin: Harry Aginta
    github: haginta

    languages:
      - idiom: English
        level: Intermediate

      - idiom: Bahasa Indonesia
        level: Native

      - idiom: Japanese
        level: Basic
footer: >
    Designed with <i class="fas fa-heart"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank" rel="nofollow">Xiaoying Riley</a>
