title: Harry Aginta

#theme: jekyll-theme-tactile
#remote_theme: poole / lanyon
#remote_theme: poole / hyde
#remote_theme: sharu725/online-cv
#remote_theme: jitinnair1/gradfolio
#remote_theme: hydecorp/hydejack
theme: minima


header_pages:
  - about.md
  - cv.md
  - research.md
